spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jspdb?serverTimezone=Asia/Seoul
    username: root
    password: mysqlroot

mybatis:
  mapper-locations:
    - classpath:mapper/**/*.xml